repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        exclude: ^.*\.md$
      - id: end-of-file-fixer
        exclude: ^.*\.md$
      - id: check-yaml
        exclude: ^pnpm-lock\.yaml$
      - id: debug-statements
      - id: double-quote-string-fixer
      - id: name-tests-test
      - id: requirements-txt-fixer

  - repo: local
    hooks:
      - id: obsidian-iconize-pnpm
        name: obsidian-iconize-pnpm
        entry: pnpm install
        language: system
        types: [file]
        pass_filenames: false
