version: "0.2"
ignorePaths: []
dictionaryDefinitions:
  - name: obsidian-iconize
    path: ./.vscode/cspell-obsidian-iconize.dict
    addWords: true
dictionaries:
  - obsidian-iconize
words: []
ignoreWords: []
import: []
